name: drives_windows
description: "A Flutter plugin get drives and network shortcuts on Windows"
version: 0.0.1
homepage: https://github.com/nini22P/drives_windows
repository: https://github.com/nini22P/drives_windows
issue_tracker: https://github.com/nini22P/drives_windows/issues

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  ffi: ^2.1.4
  flutter:
    sdk: flutter
  path: ^1.9.1
  win32: ^5.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
